M48
; DRILL file {KiCad (7.0.0)} date Sat Jul 15 19:37:35 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-15T19:37:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X203.8Y-100.62
X203.8Y-106.4
T2
X179.85Y-94.15
T3
X199.85Y-94.15
T4
X174.5Y-94.5
X174.5Y-125.5
X205.5Y-94.5
X205.5Y-125.5
T0
M30
